// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXr2Ef3ExznA7BCIPgIz6snVFEbAFD3yw',
    appId: '1:796648597747:android:674aae61710626e4426f86',
    messagingSenderId: '796648597747',
    projectId: 'crossface-70cd2',
    storageBucket: 'crossface-70cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDArtSCiOybzGCuMoAj4jGIs0w7kqAoy4Q',
    appId: '1:796648597747:ios:d5d758dceaf35aa3426f86',
    messagingSenderId: '796648597747',
    projectId: 'crossface-70cd2',
    storageBucket: 'crossface-70cd2.appspot.com',
    androidClientId: '796648597747-72drn5pd2psa4hvm97vqvvnuq8himkl0.apps.googleusercontent.com',
    iosClientId: '796648597747-9lr6epd5ic00qbfekv6m0eivb1qu00a2.apps.googleusercontent.com',
    iosBundleId: 'sergey.crossFace.app',
  );
}
